
# This Gemfile modification was generated by the `rake prepare` command
# 
class GemfileHelper
  def self.load_huginn_agent_gemspec(dependencies)
    base_path = File.expand_path('../../../', __FILE__)
    gemspec = Dir["#{base_path}/*.gemspec"].first
    previous_gems = Hash[dependencies.map { |dep| [dep.name, dep] }]
    Gem::Specification.load(gemspec).development_dependencies.each do |args|
      previous_gem = previous_gems[args.name]
      if previous_gem
        abort "Gem #{args.to_s} in #{gemspec} conflicts with huginn/Gemfile" unless previous_gem.match?(args.to_spec)
      else
        gem args.name, *args.requirements_list
      end
    end
  end
end

GemfileHelper.load_huginn_agent_gemspec(dependencies)

