
# This Gemfile modification was generated by the `rake prepare` command
#
class GemfileHelper
  def self.parse_huginn_agent_gems(dependencies)
    base_path = File.expand_path('../../../', __FILE__)
    gemspec = Dir["#{base_path}/*.gemspec"].first
    previous_gems = Hash[dependencies.map { |dep| [dep.name, dep] }]
    Gem::Specification.load(gemspec).development_dependencies.each do |args|
      next if previous_gems.key?(args.name)

      yield args.name, *args.requirements_list
    end
  end
end

GemfileHelper.parse_huginn_agent_gems(dependencies) do |args|
  gem *args
end
